version: "3.8"

services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8500:8500" # UI/API port
      - "8600:8600/tcp" # DNS port
      - "8600:8600/udp" # DNS port
    command: >
      agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
