version: "3.8"

services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8500:8500" # UI/API port
      - "8600:8600/tcp" # DNS port
      - "8600:8600/udp" # DNS port
    command: >
      agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      # RABBITMQ_DEFAULT_VHOST: /vhost
